name: CICD

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "Linting"

  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        run: echo "Validating"

  Build:
    runs-on: ubuntu-latest
    needs: [Lint, Validate]
    steps:
      - name: Compile
        run: echo "Building"

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploying Development

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploy to Staging

  DeployProd: 
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://www.myapp.com'
    steps:
      - name: Deploy
        run: echo Deploy to Production 